#!/usr/bin/env python3
"""Second citation-stripping pass: the shapes that need a human-chosen rewording.

`strip_citations.py` handles the mechanical forms (parenthetical tags, leading labels,
trailing clauses). What is left are citations woven into prose, where deleting the token
alone would leave a sentence without a subject ("Phase 2 makes the store multi-mod") or a
dangling qualifier. Each replacement below was chosen by reading the surrounding comment.

Idempotent: re-running it is a no-op once the tree is clean.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

# (pattern, replacement) applied to every tracked source file, MULTILINE.
SUBS: list[tuple[str, str]] = [
    # --- document-name citations -------------------------------------------------
    (r"//! case-insensitive NTFS\) silently fail to load \(RESEARCH\.md\n//! Pitfall 4 / PITFALLS\.md Pitfall 5\)\.",
     "//! case-insensitive NTFS) silently fail to load."),
    (r"//! something no INI \*parser\* crate round-trips \(RESEARCH rejected `rust-ini` on exactly\n//! these grounds\)\.",
     "//! something no INI *parser* crate round-trips, which is why `rust-ini` was rejected."),
    (r"//! always yields an automatic drift report \(RESEARCH\.md Pattern 1: full-pristine-or-report\)\.",
     "//! always yields an automatic drift report: full-pristine-or-report."),
    (r"//! `libloot_spike` integration test, RESEARCH A1/A3\)\.", "//! `libloot_spike` integration test)."),
    (r"/// so `is_plugin_active` after a load is the only public proxy \(07-RESEARCH Pattern 2\)\.",
     "/// so `is_plugin_active` after a load is the only public proxy."),
    (r"/// `stat` for an mtime \(07-RESEARCH Pitfall 3\) — the date", "/// `stat` for an mtime — the date"),
    (r"/// fixed name list \(07-RESEARCH Assumptions A1/A2\)\.", "/// fixed name list."),
    (r"/// wire model only \(07-RESEARCH Pattern 1 / Pitfall 2\)\.", "/// wire model only."),
    (r"stub is a SUMMARY\n    /// limitation", "stub is a known\n    /// limitation"),
    (r"//! Follows RESEARCH Pattern 1 \(oauth2 5\.0 PKCE\) verbatim\. The HTTP shape mirrors",
     "//! Uses oauth2 5.0 PKCE. The HTTP shape mirrors"),
    (r'/// `\[ASSUMED\]` `"public"` per RESEARCH A1 — the exact scope', '/// `[ASSUMED]` `"public"` — the exact scope'),
    (r"/// client \(rustls, redirects disabled\)\. See RESEARCH Pitfall — reqwest 0\.12/0\.13 split\.",
     "/// client (rustls, redirects disabled). Note the reqwest 0.12/0.13 split."),
    (r"/// `modFile` and aborted the download — RESEARCH was only MEDIUM-confidence on v2\.\)",
     "/// `modFile` and aborted the download — v2 coverage here was never confirmed.)"),
    (r"//! CRITICAL anti-pattern \(RESEARCH T-03-09 / criterion #4\): the whole body is NEVER",
     "//! CRITICAL anti-pattern: the whole body is NEVER"),
    (r'/// manually" hint rather than mis-installing the stale plan \(COLL-03; RESEARCH A3\)\.',
     '/// manually" hint rather than mis-installing the stale plan.'),
    (r"//! Two layers, per RESEARCH Pattern 6:", "//! Two layers:"),
    (r"/// Documented NexusMods per-hour request cap for API-key users \(RESEARCH A4, `\[ASSUMED\]`\)\.",
     "/// Documented NexusMods per-hour request cap for API-key users (`[ASSUMED]`)."),
    (r"// --- X-RL-\* header names \(centralised — RESEARCH A3 flags the exact casing as ASSUMED\)\. ---",
     "// --- X-RL-* header names (centralised — the exact casing is ASSUMED). ---"),
    (r"//! Classification follows the Source-type table \(RESEARCH Collection Manifest Reference\):",
     "//! Classification follows the Collection manifest's source-type table:"),
    (r"//! the pristine invariant — RESEARCH OQ3\)\. `list_plugins` MERGES",
     "//! the pristine invariant). `list_plugins` MERGES"),
    (r"/// write failure the libloot reason is surfaced verbatim for the UI-SPEC plugins\.txt error\n/// copy\.",
     "/// write failure the libloot reason is surfaced verbatim for the plugins.txt error copy."),
    (r"//! `open\(\)` would miss the file and the mod would silently do nothing \(RESEARCH\.md",
     "//! `open()` would miss the file and the mod would silently do nothing."),
    (r"//! Flatpak path\. Snap is treated as LOW-confidence \(RESEARCH\.md Assumption A2\): we do",
     "//! Flatpak path. Snap is treated as LOW-confidence: we do"),
    (r"//! This crate quarantines all Steam/Proton-layout knowledge \(per the Architectural\n//! Responsibility Map in RESEARCH\.md\)\. It auto-detects installed Steam games across\n//! native \+ Flatpak roots, offers a manual \"add game by folder\" fallback, accepts",
     "//! This crate quarantines all Steam/Proton-layout knowledge. It auto-detects installed\n//! Steam games across native + Flatpak roots, offers a manual \"add game by folder\"\n//! fallback, accepts"),
    (r"//! library root \(RESEARCH\.md Pitfall 5\)\. Resolution honors", "//! library root. Resolution honors"),
    (r"//! Crash-safety model \(CONTEXT\.md, RESEARCH\.md A7\):", "//! Crash-safety model:"),
    (r"/// The resolved availability of one Collection mod \(COLL-02; UI-SPEC §B\.3\)\.",
     "/// The resolved availability of one Collection mod."),
    (r"/// Serializable so it crosses the Tauri IPC boundary to the resolve-report UI \(UI-SPEC\n/// §B\.3\) — the report is rendered before any download\.",
     "/// Serializable so it crosses the Tauri IPC boundary to the resolve-report UI — the\n/// report is rendered before any download."),
    (r"/// `Ok\(\(\)\)` for a Premium session, or the exact Premium-required notice string \(UI-SPEC §B\.1\n/// Copywriting Contract\) for a free session\. Pure so the gate decision is unit-tested\.",
     "/// `Ok(())` for a Premium session, or the exact Premium-required notice string for a free\n/// session. Pure so the gate decision is unit-tested."),
    (r"//! Follows RESEARCH Pattern 2 verbatim, with the backend abstracted behind a small\n//! \[`KeyringBackend`\] trait so a simulated `NoStorageAccess` can be exercised in CI\n//! without a real DBus session \(RESEARCH Environment Availability\)\.",
     "//! The backend is abstracted behind a small [`KeyringBackend`] trait so a simulated\n//! `NoStorageAccess` can be exercised in CI without a real DBus session."),
    (r"/// \(UI-SPEC §A\.6\)\.\n", ""),
    (r"/// `fomod::resolve` IS the FOMOD-02 safety gate\.", "/// `fomod::resolve` IS the safety gate."),
    (r"/// `plugins\.txt` lives in the prefix AppData, never seen by the `Data/`-hash verify walk\n/// \(07-RESEARCH Pitfall 4\)\.",
     "/// `plugins.txt` lives in the prefix AppData, never seen by the `Data/`-hash verify walk."),
    # --- ticket ids woven into prose ---------------------------------------------
    (r"A single mod managed for a game\. Phase 2 makes the store multi-mod: many",
     "A single mod managed for a game. The store is multi-mod: many"),
    (r"; 1-based\. D-01\.", "; 1-based."),
    (r"acquired in-app \(NEXUS-03/06\)\.", "acquired in-app."),
    (r"the Phase-1/2 engine", "the deploy engine"),
    (r"^//! \(DEPLOY-08\)\.$", "//! casing."),
    (r"## How it decides \(D-01 / CONF-02\)", "## How it decides"),
    (r"## Safety \(T-02-06 / Security §V5/V12\)", "## Safety"),
    (r"the UI's top-of-list-wins ordering \(CONF-02 / D-01\)\.", "the UI's top-of-list-wins ordering."),
    (r"A nice-to-have warning in Phase 1;", "A nice-to-have warning;"),
    (r"via libloot \(Plan-04 primitive; PROF-02 carries\n//!    the plugin order, D-13\)\.",
     "via libloot, which carries\n//!    the plugin order."),
    (r"is the source of truth — PROF-03 \(each profile keeps its own set/order\)\.",
     "is the source of truth (each profile keeps its own set/order)."),
    (r"libloot \(Plan-04 apply_load_order; masters-first enforced internally\)\. PROF-02",
     "libloot (apply_load_order; masters-first enforced internally)."),
    (r"SFINI-04 choke point: after", "INI choke point: after"),
    (r"SFINI-04 choke point \(profile-switch", "INI choke point (profile-switch"),
    (r"SFINI-02/04 \+ WR-01: journal", "Journal"),
    (r"SFINI-02/04 choke point: after", "INI choke point: after"),
    (r"abort in the WR-01 window", "abort in the crash window"),
    (r"// WR-01 crash seam: die", "// Crash seam: die"),
    (r"## Why bottom-up `remove_dir` is safe \(GAP-01 safety argument\)", "## Why bottom-up `remove_dir` is safe"),
    (r"Phase 9's on-hardware gate \(SFVER-01\)", "the on-hardware gate"),
    (r"// T-08-01: re-verify", "// Re-verify"),
    (r"// T-08-02: never write", "// Never write"),
    (r" \(T-08-0[12]\)\"", "\""),
    (r"BL-01 REGRESSION LOCK: the deploy ranks", "REGRESSION LOCK: the deploy ranks"),
    (r"\(which would pick modA\)\. BL-01 wiring\.\"", "(which would pick modA).\""),
    (r" \(CR-02\)\"", "\""),
    (r"\(Pitfall 4 safety invariant\)", "(the safety invariant)"),
    (r" \(D-03\)\"", "\""),
    (r"reversible \(Pitfall 4 across a switch\)\.", "reversible across a switch."),
    (r"/// CR-01 REGRESSION: the LIVE", "/// REGRESSION: the LIVE"),
    (r" \(Pitfall 2\)\"", "\""),
    (r"//! PROF-03 is proven by", "//! Per-profile state is proven by"),
    (r"for the PROF-03 reproduction check", "for the reproduction check"),
    (r" winner set exactly \(PROF-03\)\"", " winner set exactly\""),
    (r"\"WR-02: a failed mid-switch", "\"a failed mid-switch"),
    (r"\"WR-02: recover_on_launch", "\"recover_on_launch"),
    (r"//! round_trip_pristine \(DEPLOY-01/02/03\):", "//! round_trip_pristine:"),
    (r"are reported only \(Pitfall 4 / \)\.", "are reported only."),
    (r"\(the GAP-01 orphan shape\)", "(the orphan shape)"),
    (r" \(T-01-16\)\"", "\""),
    (r"//! ini_activation \(SFINI-04/05\) —", "//! ini_activation —"),
    (r"// Crash in the WR-01 window:", "// Crash in the restore window:"),
    (r" byte-for-byte \(WR-01\)\"", " byte-for-byte\""),
    (r"// SFINI-04 \(unit-style\) —", "// Unit-style —"),
    (r" never deleted \(CR-01\)\"", " never deleted\""),
    (r"acute for FOMOD-02 because", "acute for the FOMOD dry-run because"),
    (r"This is the T-04-04 guard\.", "This is the ambiguous-root guard."),
    (r"//! THE Phase 1 security centerpiece\.", "//! THE security centerpiece."),
    (r"## Security model \(the Phase 1 centerpiece\)", "## Security model"),
    (r"— the Phase 1 security centerpiece\.", "— the security centerpiece."),
    (r"the only genuinely new safety-critical engine code in Phase 4\. It",
     "a self-contained safety-critical engine. It"),
    (r"<game_name>` \(Pitfall 1/2\)\.", "<game_name>`."),
    (r"masters-first internally, D-08, and", "masters-first internally, and"),
    (r"recorded snapshot date \(SFLO-02 \"masterlist from \{date\} —", "recorded snapshot date (the \"masterlist from {date} —"),
    (r"surfaced as the SFLO-02 \"masterlist", "surfaced as the \"masterlist"),
    (r"\(Phase 7 consumes this\)", "(the load-order code consumes this)"),
    (r"\*\*nexus provenance\*\* \(NEXUS-03/06\)", "**nexus provenance**"),
    (r"\*\*collections\*\* \(COLL-01/02\)", "**collections**"),
    (r"//! Phase 2 makes mods first-class:", "//! Mods are first-class:"),
    (r"//! \(CONF-02 substrate\)\. No `rusqlite`", "//! No `rusqlite`"),
    (r"/// CONF-02 substrate: list_mods returns", "/// list_mods returns"),
    (r"//! Nexus provenance store facade \(NEXUS-03/06\):", "//! Nexus provenance store facade:"),
    (r"currently-active profile \(CR-02 safety invariant\):", "currently-active profile (a safety invariant):"),
    (r"// Real mod rows \(WR-06 FK\):", "// Real mod rows (FK):"),
    (r"The DEPLOY-01/02/03 `round_trip_pristine` test and the\n//! DEPLOY-06 `crash_recovery` centerpiece",
     "The `round_trip_pristine` test and the\n//! `crash_recovery` centerpiece"),
    (r"/// GAP-01 byte-for-byte-pristine guarantee:", "/// The byte-for-byte-pristine guarantee:"),
    (r"<game_name>/` \(Pitfall 1/2\)\. On Linux", "<game_name>/`. On Linux"),
    (r"\*\*Read-only invariant:\*\* Phase 6 performs NO writes", "**Read-only invariant:** this performs NO writes"),
    (r"\(the GAP-01 repro shape\)", "(the repro shape)"),
    (r"entry point that the Plan-03\n", "entry point that the\n"),
    (r"\(includes the NEXUS-02 no-backend hard-fail\)", "(includes the no-backend hard-fail)"),
    (r"in memory only \(NEXUS-02 / D-Auth\)", "in memory only"),
    (r"//! Collection lifecycle adapters \(COLL-02/03/04/05\) — THIN per Anti-Pattern-4\.",
     "//! Collection lifecycle adapters — deliberately THIN."),
    (r"bulk Collection download \(COLL-02/03\):", "bulk Collection download:"),
    (r"^/// \(COLL-02/03\)\. Enforces", "/// Enforces"),
    (r"//! Conflict-slice adapters \(CONF-01/02/03\) —", "//! Conflict-slice adapters —"),
    (r"a game's ENABLED mods \(CONF-01\):", "a game's ENABLED mods:"),
    (r"mod's deployment rank \(CONF-02\)\. Persists", "mod's deployment rank. Persists"),
    (r"^/// engine \(CONF-03\): the deterministic", "/// engine: the deterministic"),
    (r"//! Per the Anti-Pattern-4 contract \(see `commands/mod\.rs`\): each command locks the",
     "//! Per the thin-adapter contract (see `commands/mod.rs`): each command locks the"),
    (r"through the keyring \(NEXUS-02 hard-fail-no-plaintext\)", "through the keyring (hard-fail, never plaintext)"),
    (r"^/// \(NEXUS-01 / D-Auth\)\. Idempotent", "/// Idempotent"),
    (r"honours NEXUS-02 \(keyring-only, no plaintext\)", "is keyring-only, never plaintext"),
    (r"stream→extract→stage flow \(NEXUS-04 free-user redemption\):", "stream→extract→stage flow (free-user redemption):"),
    (r"//! Profile-slice adapters \(PROF-01/02/03\) —", "//! Profile-slice adapters —"),
    (r"^//! \(D-14, shared staging\)\.", "//! (shared staging)."),
    (r"/// BUG 2: the known Bethesda", "/// The known Bethesda"),
    (r"/// BUG 2: an unmanaged/unknown", "/// An unmanaged/unknown"),
    (r"/// BUG 2: the exact recovery", "/// The exact recovery"),
    (r"//! Plugin / LOOT adapters \(PLUGIN-01/02/03\) —", "//! Plugin / LOOT adapters —"),
    (r"// SFLO-03 protected: the LIVE libloot probe", "// Protected masters: the LIVE libloot probe"),
    (r"game's plugins \(PLUGIN-01 discovery\):", "game's plugins:"),
    (r"writes as `\*` lines\)\. IN-02:", "writes as `*` lines)."),
    (r"\"WR-05: a plugins\.txt write failure", "\"a plugins.txt write failure"),
    (r"//! Download adapter \(NEXUS-03/06\) —", "//! Download adapter —"),
    (r"//! flow\. Per the Anti-Pattern-4 contract \(see `commands/mod\.rs`\): no business logic",
     "//! flow. Per the thin-adapter contract (see `commands/mod.rs`): no business logic"),
    (r"// BUG 2 fix: a Retry", "// A Retry"),
    (r"drives the WR-01 UI notice", "drives the rate-limit UI notice"),
    (r"//! headless `crates/fomod` engine\. Per the Anti-Pattern-4 contract \(see `commands/mod\.rs`\):",
     "//! headless `crates/fomod` engine. Per the thin-adapter contract (see `commands/mod.rs`):"),
    (r"available\. The NEXUS-02 hard-fail: login", "available. A hard-fail: login"),
    (r"credential\. NEXUS-02: on no-backend", "credential. On no-backend"),
    (r"kept for portability when Phase 5 adds other targets", "kept for portability if other targets are added"),
    (r"aborts \(NEXUS-03 Cancel affordance\)", "aborts (the Cancel affordance)"),
    (r"//!    \(the DEPLOY-06 startup half — an interrupted", "//!    (the startup half — an interrupted"),
    (r"BEFORE the window is shown \(DEPLOY-06 startup half\)", "BEFORE the window is shown"),
    (r"/\*\* SFLO-04 on-launch reconciliation verdict", "/** On-launch reconciliation verdict"),
    (r"\(the FOMOD-02 dry-run-before-apply gate\)", "(the dry-run-before-apply gate)"),
    (r"after the report is accepted \(COLL-02/03\)", "after the report is accepted"),
    (r"// --- NexusMods auth \(NEXUS-01/02\)\.", "// --- NexusMods auth."),
    (r"// --- NexusMods downloads \(NEXUS-03/05/06\)\.", "// --- NexusMods downloads."),
    (r"hits the NEXUS-02 no-Secret-Service hard-fail", "hits the no-Secret-Service hard-fail"),
    (r"loose-file activation \(SFINI-01/03\)\. `iniPreview`", "loose-file activation. `iniPreview`"),
    (r"loose-file activation \(SFINI-01/03\) ---", "loose-file activation ---"),
    (r"authorizes the write \(SFINI-01, Block path\)", "authorizes the write"),
    (r"behind the destructive banner \(NEXUS-02\)", "behind the destructive banner"),
    (r"clear the WR-01 notice", "clear the rate-limit notice"),
    (r"// BUG 2 fix: store the non-secret", "// Store the non-secret"),
    (r"are KEPT \(D-14, shared staging\)", "are KEPT (shared staging)"),
    (r"<!-- NEXUS-02 hard-fail: no Secret Service", "<!-- Hard-fail: no Secret Service"),
    (r"dormant until Phase 9 seeds a non-zero baseline", "dormant until a non-zero baseline is seeded"),
    (r"no \{@html\} \(T-06-05\)", "no {@html}"),
    (r"loose-file activation \(SFINI-01/03\)\. Shown", "loose-file activation. Shown"),
    (r"<!-- SFLO-04 on-launch reconciliation", "<!-- On-launch reconciliation"),
    (r"mod files are kept \(D-14\)", "mod files are kept"),
    (r"/\* NEXUS-02 destructive no-keyring banner\. \*/", "/* Destructive no-keyring banner. */"),
    (r"the same deploy-relative path \(CONF-01\)\.", "the same deploy-relative path."),
    (r"//! Conflict resolution \(CONF-01/02/03\) —", "//! Conflict resolution —"),
    (r"show \"who wins\" \(CONF-01\)\.", "show \"who wins\"."),
    (r"\(drives the CONF-01 conflict table\)", "(drives the conflict table)"),
    (r"more than one provider \(CONF-01\)\.", "more than one provider."),
    (r"as winner \(CONF-01/CONF-02\)\.", "as winner."),
    (r"flips the winner \(CONF-02\)\.", "flips the winner."),
    (r"a directory into `Data/` \(Pitfall 2:", "a directory into `Data/`:"),
    (r"multi-root WINNER SET \(CONF-03\):", "multi-root WINNER SET:"),
    (r"conflict-winner set \(CONF-03\): a full", "conflict-winner set: a full"),
    (r"remains a manual UAT item \(the Plan checkpoint / NEXUS-01\n", "remains a manual verification item (\n"),
    (r"//! conflict_redeploy \(CONF-03\) —", "//! conflict_redeploy —"),
    (r"/// CONF-03: the deterministic winner set", "/// The deterministic winner set"),
    (r"//! SFLO-04 on-launch `plugins\.txt` reconciliation", "//! On-launch `plugins.txt` reconciliation"),
    (r"/// The SFLO-04 reconciliation verdict\.", "/// The reconciliation verdict."),
    (r"//! Plugin discovery \(PLUGIN-01 discovery half\)\.", "//! Plugin discovery."),
    (r"for an EXPLICIT game \(PLUGIN-01 discovery\): same as", "for an EXPLICIT game: same as"),
    (r"The single largest technical unknown of Phase 2 is", "The single largest technical unknown was"),
    (r"//! PLUGIN-01/02 \+ masterlist integration tests", "//! Plugin + masterlist integration tests"),
    (r"//!   \* PLUGIN-02: `apply_load_order` writes", "//!   * `apply_load_order` writes"),
    (r"//!   \* PLUGIN-01: a disabled plugin is NOT", "//!   * a disabled plugin is NOT"),
    (r" state must save \(CR-01\)\"\)", " state must save\")"),
    (r"/// CR-01 \(a GENUINE reorder", "/// A GENUINE reorder"),
    (r"not rejected \(CR-01\)\"\)", "not rejected\")"),
    (r" snapshot date is surfaced \(SFLO-02\)\"", " snapshot date is surfaced\""),
    (r"//! SFLO-04 reconciliation unit tests", "//! Reconciliation unit tests"),
    (r"availability over REST v1 \(COLL-02 resolve gate\)\.", "availability over REST v1 (the resolve gate)."),
    (r"//! \(T-04-11 accept\); nothing here", "//! nothing here"),
    (r"NEVER auto-fetched \(locked decision; T-04-08 SSRF mitigation\)\.",
     "NEVER auto-fetched (a locked decision; SSRF mitigation)."),
    (r"//! Streaming download with progress \(NEXUS-03/04/06\)\.", "//! Streaming download with progress."),
    (r"\*\*keyring-free\*\* by design \(NEXUS-01/02 locked decision\)\.", "**keyring-free** by design (a locked decision)."),
    (r"/// WR-04 at the query layer: an oauth", "/// At the query layer: an oauth"),
    (r"^//! \(Pitfall 4 / T-04-09\)\.\n", ""),
    (r"the SAME \[`fomod::resolve`\] drives \(COLL-03,\n/// Pattern 6\)\.", "the SAME [`fomod::resolve`] drives."),
    (r"a higher `rank` number loses file conflicts \(Phase-2\n", "a higher `rank` number loses file conflicts (\n"),
    (r"force-win paths \(Pattern 7 / fileOverrides\)\.", "force-win paths."),
    (r"the PRODUCTION wiring for COLL-04\.", "the PRODUCTION wiring."),
    (r"/// COLL-04 wiring: `compute_collection_ranks`", "/// `compute_collection_ranks`"),
    (r"//!   \(locked decision; T-04-08 SSRF mitigation\)\. No request",
     "//!   (a locked decision; SSRF mitigation). No request"),
    (r"is never contacted \(T-04-08 SSRF mitigation\)\.", "is never contacted (SSRF mitigation)."),
    (r"/// NEXUS-01 fallback: validate_api_key", "/// Fallback: validate_api_key"),
    (r"/// NEXUS-01 fallback: a 401 maps", "/// Fallback: a 401 maps"),
    (r"NexusMods client \(NEXUS-03/05\)\.", "NexusMods client."),
    (r"\"WR-03: a 429 on one client", "\"a 429 on one client"),
    (r"\"WR-03: client B coordinates", "\"client B coordinates"),
    (r"/// BUG 1 fix: `mod_file_metadata` reads", "/// `mod_file_metadata` reads"),
    (r"/// BUG 1 fix: a 404 from the v1", "/// A 404 from the v1"),
    (r"selects it \(NEXUS-03/06 streaming gate\)\.", "selects it (the streaming gate)."),
    (r"\"CR-01: the partial file must be removed", "\"the partial file must be removed"),
    (r"availability resolver \(COLL-01/02\)\.", "availability resolver."),
    (r"`Data/` casing map \(DEPLOY-08 input\)\.", "`Data/` casing map."),
    (r"\(that arm is Phase 7's job\)", "(that arm belongs to the load-order code)"),
    (r"READ-ONLY: Phase 6 writes nothing", "READ-ONLY: this writes nothing"),
    (r"`None`\) until Phase 9 seeds the real installed build", "`None`) until the real installed build is seeded"),
    (r"reversibility is build-independent \(Phase 6 writes", "reversibility is build-independent (this writes"),
    (r"escape `<prefix>/drive_c` \(T-06-01 traversal guard\)\.", "escape `<prefix>/drive_c` (traversal guard)."),
    (r"/// \(T-06-01 traversal guard\)\. `my_games_path`", "/// (traversal guard). `my_games_path`"),
    (r"// Drift is dormant in Phase 6 \(VALIDATED_BUILD == 0\)\.", "// Drift is dormant while VALIDATED_BUILD == 0."),
    (r"canonical Data/ casing map \(DEPLOY-08 input\)\.", "canonical Data/ casing map."),
    (r"//! Collection persistence store facade \(COLL-01/02\):", "//! Collection persistence store facade:"),
    (r"/// Phase-1 \(V1-only\) DB and auto-create", "/// A V1-only DB and auto-create"),
    (r"seeded V1 state — exactly the real-world Phase-1 → upgrade\.",
     "seeded V1 state — exactly the real-world upgrade."),
    (r"/// V4 guard \(NEXUS-03/06\): reach a V3-only", "/// V4 guard: reach a V3-only"),
    (r"// The per-game canonical Data/ casing map\. Mixed-case mod directory\n    // components are rewritten to the game's REAL on-disk casing so Wine's\n    // case-sensitive open\(\) resolves them\. The map is produced by the steam crate \(Plan\n    // 02\); deploy only consumes it\.",
     "// The per-game canonical Data/ casing map. Mixed-case mod directory\n    // components are rewritten to the game's REAL on-disk casing so Wine's\n    // case-sensitive open() resolves them. The map is produced by the steam crate;\n    // deploy only consumes it."),
    # --- shapes the mechanical pass leaves for a human ---------------------------
    (r"//! Intent-before-act operation-journal protocol \+ idempotent replay \(DEPLOY-06\)\.",
     "//! Intent-before-act operation-journal protocol + idempotent replay."),
    (r"are left UNCHANGED for Phase-1 callers\.", "are left UNCHANGED for single-root callers."),
    (r"// Single-root Phase-1 deploys do not track", "// Single-root deploys do not track"),
    (r"/// Phase-1 deploys; the winning mod id for the conflict winner set — D-03\)\.",
     "/// single-root deploys; the winning mod id for the conflict winner set)."),
    (r"//! Profile-switch reconcile \(PROF-02/PROF-03\) —", "//! Profile-switch reconcile —"),
    (r"//!    \(the existing Phase-1 primitive\)\.", "//!    (the existing primitive)."),
    (r"//!    \(mod set \+ per-profile ranks via the Plan-01 store\)", "//!    (mod set + per-profile ranks via the store)"),
    (r"//!    journaled per-file primitive as Phase-1 deploy", "//!    journaled per-file primitive as deploy"),
    (r"\+ plugin order \(PROF-03\), read from\n/// the Plan-01 `profile_mod`",
     "+ plugin order, read from\n/// the `profile_mod`"),
    (r"one profile and lose in another — PROF-03\)\.", "one profile and lose in another)."),
    (r"so no file is ever deleted; T-01-16 / T-01-20\)\.", "so no file is ever deleted)."),
    (r"stay report-only, T-01-16 / T-01-20\)\.", "stay report-only)."),
    (r"//! crash_recovery \(DEPLOY-06\) — THE CENTERPIECE\.", "//! crash_recovery — THE CENTERPIECE."),
    (r"journaled per-file primitive as Phase-1 `deploy`;", "journaled per-file primitive as `deploy`;"),
    (r"//! profile_switch \(PROF-02/PROF-03\) —", "//! profile_switch —"),
    (r"/// PROF-02 \+ PROF-03 \(BLOCKING-PRISTINE\): switching", "/// BLOCKING-PRISTINE: switching"),
    (r"A's EXACT deployed set \(PROF-03\)\. ---", "A's EXACT deployed set. ---"),
    (r"are reported only \(Pitfall 4 / threat T-01-16\)\.", "are reported only."),
    (r"the orphan \(threat T-01-16 / Pitfall 4\)\.", "the orphan."),
    # --- final residue -----------------------------------------------------------
    (r"its dedicated Phase-2 profile;", "its dedicated profile;"),
    (r"The dedicated Phase-2 profile this Collection", "The dedicated profile this Collection"),
    (r"\(lowest rank wins, D-01\);", "(lowest rank wins);"),
    (r"per-target method ladder \(DEPLOY-05\)\.", "per-target method ladder."),
    (r"content-addressed vanilla store \(DEPLOY-04\)\.", "content-addressed vanilla store."),
    (r"\(NO `Data/` prefix, Pitfall 2\) so it", "(NO `Data/` prefix) so it"),
    (r"byte-for-byte untouched, SFINI-04\)\.", "byte-for-byte untouched)."),
    (r"//! Pitfall 4 / PITFALLS\.md Pitfall 5\)\.\n", ""),
    (r"a drift status \(DEPLOY-07: full-pristine-or-report\)\.", "a drift status: full-pristine-or-report."),
    (r"// DEPLOY-08: the per-game canonical", "// The per-game canonical"),
    (r"`FileEntry\.source_mod`, D-03\)\.", "`FileEntry.source_mod`)."),
    (r"^(\s*)// \(DEPLOY-08\)\. The manifest then records", r"\1// The manifest then records"),
    (r"yields a drift report \(DEPLOY-07\)\.", "yields a drift report."),
    (r"loose-file activation \(SFINI-01\.\.05\)\.", "loose-file activation."),
    (r"//! Phase-6 hardened `steam::my_games_path` resolver", "//! hardened `steam::my_games_path` resolver"),
    (r"via the Phase-6 hardened resolver", "via the hardened resolver"),
    (r"\(\[`switch_profile`\], D-15\)", "([`switch_profile`])"),
    (r"//!    Plan-03 conflict resolver,", "//!    conflict resolver,"),
    (r"the safe engine \(PROF-02\): purge", "the safe engine: purge"),
    (r"half-applied state — T-02-16\)\.", "half-applied state)."),
    (r"/// Plan-04 `loadorder::apply_load_order` primitive,", "/// The `loadorder::apply_load_order` primitive,"),
    (r"//! verify/repair drift detection \(DEPLOY-07\):", "//! verify/repair drift detection:"),
    (r"orphan walk above — T-08-03\)\.", "orphan walk above)."),
    (r"//! casefold_normalize \(DEPLOY-08\):", "//! casefold_normalize:"),
    (r"//! vanilla_restore \(DEPLOY-04\):", "//! vanilla_restore:"),
    (r"dedups before deploy, Pitfall 3\) and \(2\)", "dedups before deploy) and (2)"),
    (r"//! method_ladder \(DEPLOY-05\):", "//! method_ladder:"),
    (r"/// PROF-02: switch_profile writes", "/// switch_profile writes"),
    (r"covered by the Plan-04 loadorder", "covered by the loadorder"),
    (r"//! verify_drift \(DEPLOY-07\):", "//! verify_drift:"),
    (r"\(Carried Phase-2 gap; acute", "(Carried gap; acute"),
    (r"/// Kept SMALL and explicit \(threat T-04-04\):", "/// Kept SMALL and explicit:"),
    (r"^(\s*)// WR-01\)\. An invisible step", r"\1// An invisible step"),
    (r"\(the Plan-02 spike proved this round-trips\)", "(the spike proved this round-trips)"),
    (r"creates the AppData dir — Pitfall 2\),", "creates the AppData dir),"),
    (r"major — Pitfall 5\)\. reqwest uses", "major). reqwest uses"),
    (r"\(no OpenSSL — CLAUDE\.md\)", "(no OpenSSL)"),
    (r"dated this phase \(its Phase-6 snapshot commit date\)", "dated (its snapshot commit date)"),
    (r"//! Plugin discovery \(PLUGIN-01 discovery half, D-06\)\.", "//! Plugin discovery."),
    (r"the two Phase-7 derived booleans", "the two derived booleans"),
    (r"/// Drop the Phase-7 view-only booleans", "/// Drop the view-only booleans"),
    (r"\(matches the Plan-02 spike fixture\)\.", "(matches the spike fixture)."),
    (r"`Data/` dir \(matching the Plan-02 spike\)\.", "`Data/` dir (matching the spike)."),
    (r"\(a trust boundary, T-04-08\):", "(a trust boundary):"),
    (r"downloadable via the Phase-3 client\.", "downloadable via the Nexus client."),
    (r"the SSRF-safe classification, T-04-08\)\.", "the SSRF-safe classification)."),
    (r"straight to the Plan-02 `download_link` redemption \(Security Domain V5\)\.",
     "straight to the `download_link` redemption."),
    (r"/// Plan-01 OAuth code-exchange or a Plan-02 download — the discrimination",
     "/// An OAuth code-exchange or a download — the discrimination"),
    (r"/// threat T-03-12\)\. The parser therefore:", "/// The parser therefore:"),
    (r"\(mirrors Plan-02's local percent-encoder decision", "(a local percent-encoder decision"),
    (r"onto the EXISTING Phase-2 conflict-rank model", "onto the EXISTING conflict-rank model"),
    (r"`fileOverrides` onto the Phase-2 rank model", "`fileOverrides` onto the rank model"),
    (r"//! criterion #2; the STATE Phase-4 blocker mitigation\)\. The gate is structural: this module",
     "//! The gate is structural: this module"),
    (r"code\+state for the Plan-01 code-exchange\.", "code+state for the code-exchange."),
    (r"silently fail to load \(RESEARCH\.md Pitfall 4\)\. The deploy", "silently fail to load. The deploy"),
    (r"mixed-case mod paths under Wine \(DEPLOY-08\)\.", "mixed-case mod paths under Wine."),
    (r"BEFORE accepting it \(threat T-01-04: untrusted", "BEFORE accepting it (untrusted"),
    (r"//! Write-ahead operation journal \(DEPLOY-06\):", "//! Write-ahead operation journal:"),
    (r"//! Per-file deploy manifest \(DEPLOY-02\):", "//! Per-file deploy manifest:"),
    (r"//! Content-addressed vanilla backup ledger \(DEPLOY-04\):", "//! Content-addressed vanilla backup ledger:"),
    (r"the way Phase-1 would have,", "the way a V1 install would have,"),
    (r"exactly the real-world Phase-1 → Phase-2 upgrade\.", "exactly the real-world upgrade."),
    (r"// Seed a managed_game as Phase-1 would have persisted it\.",
     "// Seed a managed_game as a V1 install would have persisted it."),
    (r"the Phase-1 managed_game row survived untouched\.", "the V1 managed_game row survived untouched."),
    (r"\*\*deploy manifest\*\* \(DEPLOY-02\)", "**deploy manifest**"),
    (r"\*\*operation journal\*\* \(DEPLOY-06\)", "**operation journal**"),
    (r"\*\*vanilla backup ledger\*\* \(DEPLOY-04\)", "**vanilla backup ledger**"),
    (r"/// PROF-01: a game can hold", "/// A game can hold"),
    (r"/// PROF-03: two profiles hold", "/// Two profiles hold"),
    (r"HARD GATE, COLL-02\)\.", "HARD GATE)."),
    (r"NO download starts — locked decision, T-04-16\)\.", "NO download starts — a locked decision)."),
    (r"\(never auto-fetched; T-04-12\)\.", "(never auto-fetched)."),
    (r"manual steps \(NEVER fetched, T-04-12\);", "manual steps (NEVER fetched);"),
    (r"silent mis-install; COLL-03 / A3\)\.", "silent mis-install)."),
    (r"modRules at download time, Pattern 7\)\.", "modRules at download time)."),
    (r"// ── Pure / small helpers \(no business logic — Anti-Pattern-4\) ─+",
     "// ── Pure / small helpers (no business logic) ────────────────────────────────────────"),
    (r"as downloads by construction — WR-03\)\.", "as downloads by construction)."),
    (r"//! as Phase-1 `deploy` \(the safe engine", "//! as `deploy` (the safe engine"),
    (r"the EXACT Plan-02 stream→extract→stage path", "the EXACT stream→extract→stage path"),
    (r"staging path \(Plan-01 root-detection,", "staging path (root-detection,"),
    (r"//!   threat T-04-05\), then `store\.add_mod`", "//!   ), then `store.add_mod`"),
    (r"zero filesystem writes \(Plan-01 invariant\)\.", "zero filesystem writes."),
    (r"`extract::install_archive` path \(Plan-01 root-detection,", "`extract::install_archive` path (root-detection,"),
    (r"by zipping a Plan-01 fixture tree", "by zipping a fixture tree"),
    (r"/// Path to a Plan-01 fixture tree", "/// Path to a fixture tree"),
    (r"registration is pending — NEXUS-01\)\.", "registration is pending)."),
    (r"delivered by the Plan-03 deep-link handler,", "delivered by the deep-link handler,"),
    (r"logic lives in Plan-02's `run_download_to_window`, and the OAuth code-exchange\n/// lives in Plan-01's `auth::complete_oauth`\.",
     "logic lives in `run_download_to_window`, and the OAuth code-exchange\n/// lives in `auth::complete_oauth`."),
    (r"link to the shared Plan-02 download core\.", "link to the shared download core."),
    (r"the EXACT Plan-02 stream→extract→stage flow", "the EXACT stream→extract→stage flow"),
    (r"callback` to the Plan-01 OAuth code-exchange,", "callback` to the OAuth code-exchange,"),
    (r"\(masters-first; D-08\)\. Doing", "(masters-first). Doing"),
    (r"for a game \(PROF-01\) — the data source for the §D profile selector\.",
     "for a game — the data source for the profile selector."),
    (r"and return it \(PROF-01\)\. The store assigns", "and return it. The store assigns"),
    (r"the active profile \(PROF-02\), reconciling", "the active profile, reconciling"),
    (r"mod/plugin selections \(PROF-01\)\. Staged mod files are KEPT",
     "mod/plugin selections. Staged mod files are KEPT"),
    (r"/// The Plan-03 deep-link handler calls this", "/// The deep-link handler calls this"),
    (r"warn-and-continue decision, T-05-02\):", "warn-and-continue decision):"),
    (r"BEFORE the UI is served \(DEPLOY-06\)\.", "BEFORE the UI is served."),
    (r"The Phase-5 self-test below surfaces", "The self-test below surfaces"),
    (r"// Phase-5 self-test \(DIST-01 \"self-test passes\"\)\.", "// Self-test."),
    (r"never aborts startup \(locked warn-and-continue, T-05-02\)\.",
     "never aborts startup (locked warn-and-continue)."),
    (r"// --- Collections \(COLL-01\.\.05\)\. 1:1 mirrors", "// --- Collections. 1:1 mirrors"),
    (r"// --- Collections state \(UI-SPEC §B/§C, COLL-01\.\.05\)\.", "// --- Collections state."),
    (r"matching row \(UI-SPEC §B states\)\. \*/", "matching row. */"),
    (r"the Phase-1 direct path \(also the §A\.8 fallback\)", "the direct path (also the no-FOMOD fallback)"),
    (r"HARD GATE \(§A\.6, FOMOD-02\): resolve the plan", "HARD GATE: resolve the plan"),
    (r"per UI-SPEC §A\.1\. Pending until Deploy\.", "Pending until Deploy."),
    (r"<!-- Collections \(UI-SPEC §B/§C, COLL-01\.\.05\)\. The resolve report", "<!-- Collections. The resolve report"),
    (r"tree \(SFLO-03\) — a bare disabled control", "tree — a bare disabled control"),
    (r"tabindex is a deliberate, UI-SPEC-mandated focusable status affordance",
     "tabindex is a deliberate focusable status affordance"),
    (r"profile switch \(UI-SPEC §D\.2 / Copywriting\)\.", "profile switch."),
    (r"Collection uninstall \(UI-SPEC §C\.4 / Copywriting\)\.", "Collection uninstall."),
    (r"HARD GATE \(§A\.6, FOMOD-02\): the resolved file plan", "HARD GATE: the resolved file plan"),
    (r"/\* UI-SPEC download-row density \*/", "/* download-row density */"),
    (r"hit target \(UI-SPEC Spacing\) \*/", "hit target */"),
    (r"padding \(UI-SPEC Spacing exception\) \*/", "padding */"),
    (r"mirrors the Plan-02 spike fixture:", "mirrors the spike fixture:"),
    (r"handler self-test \(DIST-01 \"self-test passes\"\)\.", "handler self-test."),
    # --- artifacts left by the substitutions above --------------------------------
    (r"// repair MUST report-not-delete the orphan \(\)\.", "// repair MUST report-not-delete the orphan."),
    (r"/// Kept SMALL and explicit \(\): a too-broad list", "/// Kept SMALL and explicit: a too-broad list"),
    (r"attack surface,\n    /// \)\. The parser therefore:", "attack surface). The parser therefore:"),
    (r"no new write primitive,\n//!   \), then `store\.add_mod`", "no new write primitive),\n//!   then `store.add_mod`"),
]


def main() -> int:
    files = subprocess.run(
        ["git", "ls-files", "crates", "src-tauri/src", "frontend/src"],
        capture_output=True, text=True, check=True,
    ).stdout.split()
    files = [f for f in files if f.endswith((".rs", ".ts", ".svelte"))]
    changed = 0
    for f in files:
        path = Path(f)
        src = path.read_text()
        out = src
        for pat, rep in SUBS:
            out = re.sub(pat, rep, out, flags=re.M)
        if out != src:
            path.write_text(out)
            changed += 1
    print(f"rewrote {changed} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
